name: Update Air Quality Data

on:
  schedule:
    - cron: '0 9 * * *'  #
  workflow_dispatch:  
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Config Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies 
      run: pip install -r requirements.txt

    - name: Execute pipeline
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      run: python main.py